from data import DBClient
import datetime

def init_database():
    client = DBClient()
    if not client.is_initialized():
        # This is some filler data just to get us started.
        data = [
            {'docid': '4651397578105122424', 'date': '30/07/2017',
             'time': '21:08', 'istopnews': False, 'source': 'The Age',
             'url': 'http://www.theage.com.au/technology/innovation/carbon-emissions-artificial-intelligence-used-to-fight-deforestation-in-congo-20170730-gxlslh.html',
             'title': 'Carbon emissions: Artificial intelligence used to fight deforestation in Congo',
             'content': '\nA new technique using artificial intelligence to predict where deforestation is most likely to occur could help the Democratic Republic of Congo (DRC) preserve its shrinking rainforest and cut carbon emissions, researchers have said.\nCongo\'s rainforest, the world\'s second-largest after the Amazon, is under pressure from farms, mines, logging and infrastructure development, scientists say.Photo: Theresa Ambrose\nProtecting forests is widely seen as one of the cheapest and most effective ways to reduce the emissions driving global warming. The DRC jungle is also home to threatened species such as gorillas.\nBut conservation efforts in DRC have suffered from a lack of precise data on which areas of the country\'s vast territory are most at risk of losing their pristine vegetation, said Thomas Maschler, a researcher at the World Resources Institute (WRI).\n"We don\'t have fine-grain information on what is actually happening on the ground," he told the Thomson Reuters Foundation.\nTo address the problem Maschler and other scientists at the Washington-based WRI used a computer algorithm based on machine learning, a type of artificial intelligence.\n\nThe computer was fed inputs, including satellite-derived data, detailing how the landscape in a number of regions, accounting for almost a fifth of the country, had changed between 2000 and 2014.\nThe program was asked to use the information to analyse links between deforestation and the factors driving it, such as proximity to roads or settlements, and to produce a detailed map forecasting future losses.\n\nYou will now receive updates from\n\nTechnology Newsletter\n\nTechnology Newsletter\n\nGet the latest news and updates emailed straight to your inbox.\n\nOverall the application predicted that woods covering an area roughly the size of Luxembourg would be cut down by 2025 - releasing 205 million metric tons of carbon dioxide into the atmosphere.\nThe study improved on earlier predictions that could only forecast average deforestation levels in DRC over large swathes of land, said Maschler.\n"Now, we can say: \'actually the corridor along the road between these two villages is at risk\'," Maschler said by phone late on Thursday.\nThe analysis will allow conservation groups to better decide where to focus their efforts and help the government shape its land use and climate change policy, said scientist Elizabeth Goldman who co-authored the research.\nThe DRC has pledged to restore 3 million hectares of forest to reduce carbon emissions under the 2015 Paris Agreement, she said.\nBut Goldman said the benefits of doing that would be outweighed by more than six times by simply cutting predicted forest losses by 10 per cent.\nThomson Reuters Foundation\n',
             'sindices': [{'name': 'Photo', 'count': 1.0, 'score': 1.0},
                          {'name': 'World Resources Institute', 'count': 1.0, 'score': 0.0},
                          {'name': 'Maschler', 'count': 3.0, 'score': -2.0},
                          {'name': 'Goldman', 'count': 1.0, 'score': 0.0}, {'name': 'WRI', 'count': 1.0, 'score': 0.0},
                          {'name': 'Congo', 'count': 2.0, 'score': -2.0},
                          {'name': 'Thomson Reuters Foundation', 'count': 2.0, 'score': 0.0},
                          {'name': 'Paris Agreement', 'count': 1.0, 'score': 0.0},
                          {'name': 'Luxembourg', 'count': 1.0, 'score': 0.0},
                          {'name': 'Democratic Republic of Congo', 'count': 1.0, 'score': 2.0},
                          {'name': 'Amazon', 'count': 1.0, 'score': 0.0},
                          {'name': 'Washington-based WRI', 'count': 1.0, 'score': 0.0},
                          {'name': 'Theresa Ambrose', 'count': 1.0, 'score': 1.0},
                          {'name': 'Elizabeth Goldman', 'count': 1.0, 'score': 0.0},
                          {'name': 'DRC', 'count': 5.0, 'score': 0.0},
                          {'name': 'Thomas Maschler', 'count': 1.0, 'score': 0.0},
                          {'name': 'Thursday', 'count': 1.0, 'score': 0.0}],
             'datetime': datetime.datetime(2017, 7, 30, 21, 8)},
            {'docid': '4651397578105122432', 'date': '30/07/2017',
             'time': '21:08', 'istopnews': False, 'source': 'New Daily',
             'url': 'http://thenewdaily.com.au/news/world/2017/07/31/vladimir-putin-expels-us-diplomats/',
             'title': 'Vladimir Putin orders expulsion of 755 US diplomats',
             'content': '\nPresident Vladimir Putin says Russia will expel 755 US diplomatic staff and may consider imposing additional measures against the United States as a response to new US sanctions.\nMoscow ordered the US to cut hundreds of diplomatic staff and said it would seize two US diplomatic properties after the US House of Representatives and the Senate approved new sanctions on Russia.\nMr Putin told Russia\'s Vesti TV in an interview released Sunday local time that 755 US diplomatic and technical staff would have to leave Russia by September 1.\n"Because more than 1000 workers - diplomats and support staff - were working and are still working in Russia, 755 must stop their activity in the Russian Federation," he said.\nThe new US sanctions were in part a response to conclusions by US intelligence agencies that Russia meddled in the 2016 US presidential election, and to further punish Russia for its annexation of Crimea in 2014.\nMoscow said on Friday that the United States must reduce its diplomatic staff in Russia to 455 people, matching the number of Russian diplomats left in the United States after Washington expelled 35 Russians in December.\nOn Friday, an official at the US Embassy, who did not wish to be identified, said the embassy employed around 1100 diplomatic and support staff in Russia, including Russian and US citizens.\nMr Putin said that Russia could take more measures against the United States but not at the moment.\nHe repeated that the US sanctions were a step to worsening relations between the two countries.\nHowever, he said Moscow and Washington were achieving results on cooperation even "in this quite difficult situation".\nThe creation of the Southern de-escalation zone in Syria showed a concrete result of the joint work between the two countries, Mr Putin said.\n',
             'sindices': [{'name': 'Moscow', 'count': 3.0, 'score': 3.0},
                          {'name': 'Russian', 'count': 3.0, 'score': 0.0},
                          {'name': 'Russian Federation', 'count': 1.0, 'score': 0.0},
                          {'name': 'September 1', 'count': 1.0, 'score': 0.0},
                          {'name': 'President Vladimir Putin', 'count': 1.0, 'score': -1.0},
                          {'name': 'United States', 'count': 4.0, 'score': 1.0},
                          {'name': 'Senate', 'count': 1.0, 'score': -2.0},
                          {'name': 'Sunday', 'count': 1.0, 'score': 0.0},
                          {'name': 'Mr Putin', 'count': 3.0, 'score': 0.0},
                          {'name': 'US House of Representatives', 'count': 1.0, 'score': 2.0},
                          {'name': 'Syria', 'count': 1.0, 'score': 0.0}, {'name': 'Friday', 'count': 2.0, 'score': 0.0},
                          {'name': 'US Embassy', 'count': 1.0, 'score': 0.0},
                          {'name': "Russia's Vesti TV", 'count': 1.0, 'score': 0.0},
                          {'name': 'Russia', 'count': 9.0, 'score': -1.0},
                          {'name': 'December', 'count': 1.0, 'score': -1.0},
                          {'name': 'Crimea', 'count': 1.0, 'score': -2.0},
                          {'name': 'Vladimir Putin', 'count': 1.0, 'score': -2.0},
                          {'name': 'Washington', 'count': 2.0, 'score': 1.0}],
             'datetime': datetime.datetime(2017, 7, 30, 21, 8)},
            {'docid': '4651397582400089753', 'date': '30/07/2017',
             'time': '21:09', 'istopnews': False, 'source': 'Herald Sun',
             'url': 'http://www.heraldsun.com.au/lifestyle/health/shock-new-data-shows-the-number-of-aussie-methamphetamine-users-killed-has-doubled-in-six-years/news-story/45e954c668412ab92a8ddf3b74a32b43',
             'title': 'Surprising thing killing ice users',
             'content': '\nTHE number of Australians killed as a result of methamphetamine use has doubled in just six years, shocking new data shows.\nProfessor Shane Darke from the National Drug and Alcohol Research Centre described the findings, released today in the academic journal Addiction, as a public health crisis.\nHis team examined 1649 fatalities linked to  between 2009 and 2015 and found a mortality rate up to six times greater than the general population.\n"I hear it occasionally said that the extent of the methamphetamine problem has been overstated, but I think this many identified cases over seven years shows we have a major problem," Professor Darke said.\nOn average, each death represented 44 years of lost individual life, he said.\nThere are different types of methamphetamine, generally distinguished by their appearance and purity, and the drug crystal meth - commonly known as ice - is the most popular among users.\n\nProfessor Darke found a "hidden danger" in meth-related deaths, in the form of damage to vital organs from even modest amounts of the drug.\nIn 22 per cent of cases, \'natural\' disease like cardiac arrest or stroke were the common causes of death, Professor Darke said.\n"Many users may be unaware that heart disease is a major factor in methamphetamine-related death."\nCurrent projections indicate there are about 300,000  across the country.\nPopular perceptions centre on violence and while deaths from accident, misadventure and suicide are high, almost half of meth users perished from overdose.\n"Basically, the person becomes unbearably hot and their temperature spikes. They have trouble breathing and they may fit.\n"Even a very little amount can kill you - it can engender a heart attack."\nHe fears the rates of death - which rose year-on-year until 2012 when they plateued at dangerously high levels - will not improve without greater awareness.\n"But there are long-term impacts too," Professor Darke said.\n"Even if everyone stopped using methamphetamines today, we\'re looking at a number of individuals with serious damage to their hearts."\nAnother troubling finding surrounded the 300 identified suicides in the data, he said.\nWhen looking at the methods those people used to take their own lives, he observed unusually violent and impulsive acts.\n"I\'ve done research on suicide for many years and one thing that stood out, which I\'ve never seen before ... is the disinhibition, impulsivity, and aggression shown in these cases.\n"It\'s just not typical of suicide."\nWhile meth deaths skewed fairly young, there were no commonalities when it came to location or socio-economic status, he said.\nTests carried out on wastewater last week (to determine the prevalence of drug use) showed South Australia and Western Australia were home to the nation\'s biggest meth users.\nAlmost half of those occurred in regional or rural locations and a large number of users were gainfully employed when they died.\nHowever very few were in treatment, showing the need for greater funding for services.\n"We think there are aspects of the dangers of methamphetamine that people - particularly users - aren\'t aware of," he said.\n"This is the tip of the iceberg. I think this issue is something from which the effects will be felt for decades to come."\nIf you or someone you know needs help, call the Alcohol and Drug Foundation on 1300 85 85 84 or visit adf.org.au\nOriginally published as\n',
             'sindices': [{'name': 'Australians', 'count': 1.0, 'score': -3.0},
                          {'name': 'Western Australia', 'count': 1.0, 'score': -4.0},
                          {'name': 'Drug Foundation', 'count': 1.0, 'score': 0.0},
                          {'name': 'South Australia', 'count': 1.0, 'score': 0.0},
                          {'name': 'Professor Shane Darke', 'count': 1.0, 'score': 0.0},
                          {'name': 'Alcohol Research Centre', 'count': 1.0, 'score': 0.0},
                          {'name': 'Professor Darke', 'count': 4.0, 'score': -2.0},
                          {'name': 'National Drug', 'count': 1.0, 'score': 0.0}],
             'datetime': datetime.datetime(2017, 7, 30, 21, 9)},
            {'docid': '4651397582400089775', 'date': '30/07/2017',
             'time': '21:09', 'istopnews': True, 'source': 'Northern Territory News',
             'url': 'http://www.ntnews.com.au/news/national/sydney-counterterrorism-raids-jihadis-plotted-meat-mincer-bomb-attack-to-blow-up-flight/news-story/adc1491aa8be75032a94dde8f957f517',
             'title': "Jihadis' 'meat mincer bomb plot'",
             'content': '\nTWO would-be father and son terror teams linked by marriage are allegedly behind a plot to blow up an international flight out of Sydney using a .\nUntil last week the four men - the fathers aged in their 40s - were totally unknown to the nation\'s counter-terrorism authorities with only one conviction for negligent driving between them.\nBut that all changed when police picked up a "small piece of intelligence" about the possible "Islamist-inspired" plot to use a crude homemade bomb. It is believed the plot involved smuggling the device onto a flight bound for the Middle East, possibly Dubai, hidden in carry-on luggage.\nWith the men under surveillance, police decided to arrest them on Saturday because the risk to public safety was too high.\nFive homes were raided in Surry Hills, Punchbowl, Wiley Park and Lakemba.\n\n"There was a serious threat that had to be shut down," one senior officer said.\nIt is understood the plan was to use wood scrapings and explosive material inside a piece of kitchen equipment, such as a mincing machine.\nPolice seized several items from one home, including the bottom and top half of a domestic grinder and a box containing a "multi-mincer" used to make sausages. They also took away a number of handwritten notes, two phones, an iPad, two mobile phone SIM packs and vehicle registration and insurance papers.\n\nMaterial to make a bomb, which was understood to be "ready to go", was allegedly found at a house in Cleveland St, Surry Hills, where one man was arrested. It is believed his son was also detained at a different address\n\nThe other two men were arrested in Western Sydney, one in Lakemba dressed only in a towel.\nAnother theory reported last night was that the men were planning to bring down a plane by gassing the passengers. The Australian reported the explosive device would emit a toxic, sulphur-based gas that could kill or immobilise everyone on the aircraft.\nThe four have not yet been charged, with  before they have to be charged or released under Commonwealth laws.\nPrime Minister  as he beefed up security at all major airports around the country. Police are concerned that the men were cleanskins, unknown to them and not associated with known groups.\n"With terrorism you can\'t wait, you can\'t wait to put the whole puzzle together, you do have to go early because if you get it wrong the consequences are severe," NSW Police Commissioner Mick Fuller said.\n\n"You need to make the decision at some stage, when is the right time to go. Both (Australian Federal Police) and NSW Police agreed last night was the right time to go."\nAFP Commissioner Andrew Colvin said the plan was "Islamist-inspired" and likely targeted the aviation industry. "We do believe it is Islamic-inspired terrorism. I think this (threat) was credible," he said. There was shock in Surry Hills, where neighbours said the family had lived there since the 1970s. One neighbour said he was not aware of any extremist links.\n"Never in my life would I have expected this ... they\'re a very nice family," he said.\nAt Lakemba, police locked down an entire apartment block, forcing residents to show ID cards to gain entry. Forensic teams carrying ladders and tools searched a mid-level unit and officers were seen digging in the garden. One neighbour said he often saw people in religious robes gather outside.\n"You\'d have 15 or 20 of them talking outside and they would all go into the unit together," he said.\nOne couple, who live in the Craig St, Punchbowl, unit raided on Saturday, said police stormed into their home about 5pm and left about 11.30pm. Neither of them was arrested.\nThe wife said her 66-year-old husband was on his iPad when police arrived and dragged him outside. She said she didn\'t know why police had searched their home. "We\'re not bad. We put scarf on, that\'s our religion ... you go to the church, I go to the mosque, that\'s it," she said.\nA , lived in a unit with his brother and nurtured a community of about 15 stray cats, neighbours said.\n"He was a strange man, he never looked at you in the eye when you spoke to him," one neighbour said.\n- Additional reporting Nick Hansen, Danielle Gusmaroli and Jack Houghton\nOriginally published as\n',
             'sindices': [{'name': 'ID', 'count': 1.0, 'score': 0.0},
                          {'name': 'Australians', 'count': 1.0, 'score': -1.0},
                          {'name': 'AFP Commissioner Andrew Colvin', 'count': 1.0, 'score': 0.0},
                          {'name': 'Punchbowl', 'count': 2.0, 'score': -1.0},
                          {'name': 'Nick Hansen', 'count': 1.0, 'score': 0.0},
                          {'name': 'Middle East', 'count': 1.0, 'score': 0.0},
                          {'name': 'Dubai', 'count': 1.0, 'score': 0.0},
                          {'name': 'Islamist-inspired', 'count': 2.0, 'score': -2.0},
                          {'name': 'Cleveland St', 'count': 1.0, 'score': 0.0},
                          {'name': 'iPad', 'count': 2.0, 'score': 0.0},
                          {'name': 'Prime Minister', 'count': 1.0, 'score': -1.0},
                          {'name': 'NSW Police Commissioner Mick Fuller', 'count': 1.0, 'score': 0.0},
                          {'name': 'Western Sydney', 'count': 1.0, 'score': 0.0},
                          {'name': 'SIM', 'count': 1.0, 'score': 0.0},
                          {'name': 'Wiley Park', 'count': 1.0, 'score': 0.0},
                          {'name': 'Islamic-inspired', 'count': 1.0, 'score': 0.0},
                          {'name': 'Saturday', 'count': 2.0, 'score': -1.0},
                          {'name': 'Commonwealth', 'count': 1.0, 'score': -1.0},
                          {'name': 'Danielle Gusmaroli', 'count': 1.0, 'score': 0.0},
                          {'name': 'Lakemba', 'count': 3.0, 'score': 0.0},
                          {'name': 'Surry Hills', 'count': 3.0, 'score': -2.0},
                          {'name': 'Australian Federal Police', 'count': 1.0, 'score': 4.0},
                          {'name': 'Craig St', 'count': 1.0, 'score': 0.0},
                          {'name': 'Jack Houghton', 'count': 1.0, 'score': 0.0},
                          {'name': 'NSW Police', 'count': 1.0, 'score': 4.0},
                          {'name': 'Sydney', 'count': 1.0, 'score': -6.0}],
             'datetime': datetime.datetime(2017, 7, 30, 21, 9)},
            {'docid': '4651397582400089818', 'date': '30/07/2017',
             'time': '21:09', 'istopnews': True, 'source': 'Banking Day',
             'url': 'http://www.bankingday.com/nl06_news_selected.php?act=2&stream=70&selkey=22686&hlc=2&hlw=',
             'title': 'Commercial mortgage vibe sticks',
             'content': "\nThis content requires an active Banking Day subscription. Login below or .\n\nI'm a returning subscriber\n\nRequest a free trial\n\nEmailing you the news at 7am.\nCovering core lending and funding issues, strategy, payments, regulation, risk management, IT, marketing and more.\nOriginal news and summaries of major stories from other media - ditch your newspaper subscriptions.\n\nFocused on banking and finance, saving you the time spent wading through newspapers and other services.\nWith reporting from former editors and senior writers from the AFR and The Australian.\nConfigured for your phone, laptop and PC.\n",
             'sindices': [{'name': 'PC', 'count': 1.0, 'score': 0.0},
                          {'name': 'Australians', 'count': 1.0, 'score': 0.0},
                          {'name': 'Banking Day', 'count': 1.0, 'score': 1.0},
                          {'name': 'AFR', 'count': 1.0, 'score': 0.0}],
             'datetime': datetime.datetime(2017, 7, 30, 21, 9)},
            {'docid': '4651397586695057129', 'date': '30/07/2017',
             'time': '21:10', 'istopnews': False, 'source': 'Courier Mail',
             'url': 'http://www.couriermail.com.au/lifestyle/health/shock-new-data-shows-the-number-of-aussie-methamphetamine-users-killed-has-doubled-in-six-years/news-story/45e954c668412ab92a8ddf3b74a32b43',
             'title': 'Surprising thing killing ice users',
             'content': '\nIce Nation: Australia\'s drug epidemic\n\nTHE number of Australians killed as a result of methamphetamine use has doubled in just six years, shocking new data shows.\n\nProfessor Shane Darke from the National Drug and Alcohol Research Centre described the findings, released today in the academic journal Addiction, as a public health crisis.\n\nHis team examined 1649 fatalities linked to  between 2009 and 2015 and found a mortality rate up to six times greater than the general population.\n\n"I hear it occasionally said that the extent of the methamphetamine problem has been overstated, but I think this many identified cases over seven years shows we have a major problem," Professor Darke said.\n\nOn average, each death represented 44 years of lost individual life, he said.\n\nThere are different types of methamphetamine, generally distinguished by their appearance and purity, and the drug crystal meth - commonly known as ice - is the most popular among users.\n\nProfessor Darke found a "hidden danger" in meth-related deaths, in the form of damage to vital organs from even modest amounts of the drug.\n\nIn 22 per cent of cases, \'natural\' disease like cardiac arrest or stroke were the common causes of death, Professor Darke said.\n\n"Many users may be unaware that heart disease is a major factor in methamphetamine-related death."\n\nCurrent projections indicate there are about 300,000  across the country.\n\nPopular perceptions centre on violence and while deaths from accident, misadventure and suicide are high, almost half of meth users perished from overdose.\n\n"Basically, the person becomes unbearably hot and their temperature spikes. They have trouble breathing and they may fit.\n\n"Even a very little amount can kill you - it can engender a heart attack."\n\nHe fears the rates of death - which rose year-on-year until 2012 when they plateued at dangerously high levels - will not improve without greater awareness.\n\n"But there are long-term impacts too," Professor Darke said.\n\n"Even if everyone stopped using methamphetamines today, we\'re looking at a number of individuals with serious damage to their hearts."\n\nAnother troubling finding surrounded the 300 identified suicides in the data, he said.\n\nWhen looking at the methods those people used to take their own lives, he observed unusually violent and impulsive acts.\n\n"I\'ve done research on suicide for many years and one thing that stood out, which I\'ve never seen before ... is the disinhibition, impulsivity, and aggression shown in these cases.\n\n"It\'s just not typical of suicide."\n\nWhile meth deaths skewed fairly young, there were no commonalities when it came to location or socio-economic status, he said.\n\nTests carried out on wastewater last week (to determine the prevalence of drug use) showed South Australia and Western Australia were home to the nation\'s biggest meth users.\n\nAlmost half of those occurred in regional or rural locations and a large number of users were gainfully employed when they died.\n\nHowever very few were in treatment, showing the need for greater funding for services.\n\n"We think there are aspects of the dangers of methamphetamine that people - particularly users - aren\'t aware of," he said.\n\n"This is the tip of the iceberg. I think this issue is something from which the effects will be felt for decades to come."\n\nIf you or someone you know needs help, call the Alcohol and Drug Foundation on 1300 85 85 84 or visit adf.org.au\n\nLike this:\n\nLike Loading...\n\n',
             'sindices': [{'name': 'Australians', 'count': 1.0, 'score': -3.0},
                          {'name': 'Western Australia', 'count': 1.0, 'score': -4.0},
                          {'name': 'Drug Foundation', 'count': 1.0, 'score': 0.0},
                          {'name': 'South Australia', 'count': 1.0, 'score': 0.0},
                          {'name': 'Australia', 'count': 1.0, 'score': -3.0},
                          {'name': 'Professor Shane Darke', 'count': 1.0, 'score': 0.0},
                          {'name': 'Alcohol Research Centre', 'count': 1.0, 'score': 0.0},
                          {'name': 'Professor Darke', 'count': 4.0, 'score': -2.0},
                          {'name': 'National Drug', 'count': 1.0, 'score': 0.0}],
             'datetime': datetime.datetime(2017, 7, 30, 21, 10)},
            {'docid': '4651397586695057146', 'date': '30/07/2017',
             'time': '21:10', 'istopnews': True, 'source': 'Banking Day',
             'url': 'http://www.bankingday.com/nl06_news_selected.php?act=2&stream=20&selkey=22684&hlc=2&hlw=',
             'title': 'WIB selective with Asia',
             'content': "\nThis content requires an active Banking Day subscription. Login below or .\n\nI'm a returning subscriber\n\nRequest a free trial\n\nEmailing you the news at 7am.\nCovering core lending and funding issues, strategy, payments, regulation, risk management, IT, marketing and more.\nOriginal news and summaries of major stories from other media - ditch your newspaper subscriptions.\n\nFocused on banking and finance, saving you the time spent wading through newspapers and other services.\nWith reporting from former editors and senior writers from the AFR and The Australian.\nConfigured for your phone, laptop and PC.\n",
             'sindices': [{'name': 'PC', 'count': 1.0, 'score': 0.0},
                          {'name': 'Australians', 'count': 1.0, 'score': 0.0},
                          {'name': 'WIB', 'count': 1.0, 'score': 0.0},
                          {'name': 'Banking Day', 'count': 1.0, 'score': 1.0},
                          {'name': 'Asia', 'count': 1.0, 'score': 0.0}, {'name': 'AFR', 'count': 1.0, 'score': 0.0}],
             'datetime': datetime.datetime(2017, 7, 30, 21, 10)},
            {'docid': '4651397586695057162', 'date': '30/07/2017',
             'time': '21:10', 'istopnews': True, 'source': 'Coffs Coast Advocate',
             'url': 'http://www.coffscoastadvocate.com.au/news/meth-deaths-double-six-years/3206803/',
             'title': 'Meth deaths double in six years',
             'content': '\nTHE number of Australians killed as a result of methamphetamine use has doubled in just six years, shocking new data shows.\n\nProfessor Shane Darke from the National Drug and Alcohol Research Centre described the findings, released today in the academic journal Addiction, as a public health crisis.\n\nHis team examined 1649 fatalities linked to the illicit drug between 2009 and 2015 and found a mortality rate up to six times greater than the general population.\n\n"I hear it occasionally said that the extent of the methamphetamine problem has been overstated, but I think this many identified cases over seven years shows we have a major problem," Professor Darke said.\n\nOn average, each death represented 44 years of lost individual life, he said.\n\nThere are different types of methamphetamine, generally distinguished by their appearance and purity, and the drug crystal meth - commonly known as ice - is the most popular among users.\n\nProfessor Darke found a "hidden danger" in meth-related deaths, in the form of damage to vital organs from even modest amounts of the drug.\n\nIn 22 per cent of cases, \'natural\' disease like cardiac arrest or stroke were the common causes of death, Professor Darke said.\n\n"Many users may be unaware that heart disease is a major factor in methamphetamine-related death."\n\nSignificant focus has been placed on policing but more needs to be done to treat drug usage.News Corp Australia\n\nCurrent projections indicate there are about 300,000 regular users of meth across the country.\n\nPopular perceptions centre on violence and while deaths from accident, misadventure and suicide are high, almost half of meth users perished from overdose.\n\n"Basically, the person becomes unbearably hot and their temperature spikes. They have trouble breathing and they may fit.\n\n"Even a very little amount can kill you - it can engender a heart attack."\n\nHe fears the rates of death - which rose year-on-year until 2012 when they plateued at dangerously high levels - will not improve without greater awareness.\n\n"But there are long-term impacts too," Professor Darke said.\n\n"Even if everyone stopped using methamphetamines today, we\'re looking at a number of individuals with serious damage to their hearts."\n\nAnother troubling finding surrounded the 300 identified suicides in the data, he said.\n\nWhen looking at the methods those people used to take their own lives, he observed unusually violent and impulsive acts.\n\n"I\'ve done research on suicide for many years and one thing that stood out, which I\'ve never seen before ... is the disinhibition, impulsivity, and aggression shown in these cases.\n\n"It\'s just not typical of suicide."\nPolice bust uncovers meth and MDMA:\n\nWhile meth deaths skewed fairly young, there were no commonalities when it came to location or socio-economic status, he said.\n\nTests carried out on wastewater last week (to determine the prevalence of drug use) showed South Australia and Western Australia were home to the nation\'s biggest meth users.\n\nAlmost half of those occurred in regional or rural locations and a large number of users were gainfully employed when they died.\n\nHowever very few were in treatment, showing the need for greater funding for services.\n\n"We think there are aspects of the dangers of methamphetamine that people - particularly users - aren\'t aware of," he said.\n\n"This is the tip of the iceberg. I think this issue is something from which the effects will be felt for decades to come."\n\nIf you or someone you know needs help, call the Alcohol and Drug Foundation on 1300 85 85 84 or visit adf.org.au\n\n',
             'sindices': [{'name': 'Australians', 'count': 1.0, 'score': -3.0},
                          {'name': 'Western Australia', 'count': 1.0, 'score': -4.0},
                          {'name': 'MDMA', 'count': 1.0, 'score': -1.0},
                          {'name': 'Drug Foundation', 'count': 1.0, 'score': 0.0},
                          {'name': 'South Australia', 'count': 1.0, 'score': 0.0},
                          {'name': 'News Corp Australia', 'count': 1.0, 'score': 0.0},
                          {'name': 'Professor Shane Darke', 'count': 1.0, 'score': 0.0},
                          {'name': 'Alcohol Research Centre', 'count': 1.0, 'score': 0.0},
                          {'name': 'Professor Darke', 'count': 4.0, 'score': -2.0},
                          {'name': 'National Drug', 'count': 1.0, 'score': 0.0}],
             'datetime': datetime.datetime(2017, 7, 30, 21, 10)},
            {'docid': '4651397586695057202', 'date': '30/07/2017',
             'time': '21:10', 'istopnews': True, 'source': 'Ipswich Queensland Times',
             'url': 'http://www.qt.com.au/news/mayor-on-monday-historic-disaster-will-never-be-fo/3206650/',
             'title': 'Mayor on Monday: Historic disaster will never be forgotten',
             'content': "\nTODAY marks the 45th anniversary of the Box Flat mine disaster when a massive explosion occurred at 2.47am on July 31, 1972.\n\nIt was so large it rocked homes in Ipswich causing some to think it was an earthquake. It also registered on the University of Queensland seismograph at Mount Nebo.\n\nAt the time of the disaster it was deeply felt by the people of Ipswich when it was reported that men and women wept unashamedly at the loss of so many lives in the streets of this city.\n\nLater this morning a special service will be held at the new Ipswich-Rosewood Coalminers Memorial in Limestone Park to remember those whose lives were taken by this tragic accident.\n\nRugby winner all round\n\nLAST Friday it was great to visit Rangers Rugby Union Club at Woodend for the presentation at the school-based 7 a side competition in two age groups.\n\nThe under 10s played for the Rangers Cup and under 12s were competing for the Mayor's Shield.\n\nThis annual Festival of Rugby is a highlight on the sporting calendar for the participating schools.\n\nSticking with a the rugby theme, new seating has been installed at Evan Marginson Park Goodna which will come in handy for Goodna Gladiators Rugby Union Club, the Goodna Jacaranda Festival at the end of October as well as Goodna Little Athletics.\n\nPark 2 park family fun success\n\nCONGRATULATIONS to the Ipswich Hospital Foundation on another successful Park 2 Park event yesterday.\n\nThis event has grown to become one of most well-known of its type in South East Queensland.\n\nFrom the serious athlete to fun with the family Park 2 Park now boasts seven events from the half marathon to family challenge and mascot marathon.\n\nIf we are to achieve the goal of being Australia's healthiest community then Park 2 Park and other similar events will help the community get involved in healthy lifestyle choices and promote regular exercise.\n\nI hope the kids at Kindy Patch 2 at Springfield Central learnt a little about bee keeping last week after I received an email from centre director Sarah inviting me to give a talk about one of my favourite subjects.\n\nThey were very interested in the honey bees and native Australian bees and why they are so important to our environment.\n\nI am always happy to help local children learn more about bees as this has been my hobby for over 50 years.\n\n",
             'sindices': [{'name': 'Monday', 'count': 1.0, 'score': 0.0},
                          {'name': 'Mount Nebo', 'count': 1.0, 'score': 0.0},
                          {'name': 'Rangers Cup', 'count': 1.0, 'score': 0.0},
                          {'name': 'Rangers Rugby Union Club', 'count': 1.0, 'score': 3.0},
                          {'name': 'Australians', 'count': 1.0, 'score': 2.0},
                          {'name': 'Park 2', 'count': 1.0, 'score': 5.0},
                          {'name': 'October', 'count': 1.0, 'score': 0.0},
                          {'name': "Mayor's Shield", 'count': 1.0, 'score': -2.0},
                          {'name': 'July 31', 'count': 1.0, 'score': -1.0},
                          {'name': 'Park 2 Park', 'count': 3.0, 'score': 4.0},
                          {'name': 'Springfield Central', 'count': 1.0, 'score': -4.0},
                          {'name': 'University of Queensland', 'count': 1.0, 'score': 0.0},
                          {'name': 'Sarah', 'count': 1.0, 'score': 0.0},
                          {'name': 'Australia', 'count': 1.0, 'score': 3.0},
                          {'name': 'Goodna Jacaranda Festival', 'count': 1.0, 'score': 0.0},
                          {'name': 'Ipswich Hospital Foundation', 'count': 1.0, 'score': 2.0},
                          {'name': 'Festival of Rugby', 'count': 1.0, 'score': 0.0},
                          {'name': 'Box Flat', 'count': 1.0, 'score': -3.0},
                          {'name': 'South East Queensland', 'count': 1.0, 'score': 0.0},
                          {'name': 'Limestone Park', 'count': 1.0, 'score': 0.0},
                          {'name': 'Friday', 'count': 1.0, 'score': 3.0},
                          {'name': 'Kindy Patch 2', 'count': 1.0, 'score': -6.0},
                          {'name': 'Goodna Little Athletics', 'count': 1.0, 'score': 0.0},
                          {'name': 'Ipswich', 'count': 2.0, 'score': 0.0},
                          {'name': 'Evan Marginson Park Goodna', 'count': 1.0, 'score': 0.0},
                          {'name': 'Goodna Gladiators Rugby Union Club', 'count': 1.0, 'score': 2.0},
                          {'name': 'Ipswich-Rosewood Coalminers Memorial', 'count': 1.0, 'score': 0.0},
                          {'name': 'Woodend', 'count': 1.0, 'score': 0.0}],
             'datetime': datetime.datetime(2017, 7, 30, 21, 10)},
            {'docid': '4651397590990024516', 'date': '30/07/2017',
             'time': '21:11', 'istopnews': False, 'source': 'Brisbane Times',
             'url': 'http://www.brisbanetimes.com.au/lifestyle/fashion/good-jeans-the-denim-trend-that-helps-the-planet-20170723-gxh7xq.html',
             'title': "You've heard of slow food. This is slow denim.",
             'content': '\nI love a good perve inside a celebrity\'s wardrobe, thanks to the glossy mags. There\'s always some magical Portobello Road Market find - those that you, as a mere mortal, will never be able to nab, plus, quite often, a staggering number of jeans; it\'s not unheard of for some fashionistas to have .\n\nOver the rainbow ... Kesha wearing a pair of colourful, customised overalls at LAX. Photo: Getty Images\n\nBut since learning about the  can have on the planet - the toxic chemicals and water usage in the dyeing process, the impact of so-called "distressing" techniques, and so on - I\'ve had a massive rethink about how many pairs of jeans I "need".\nI probably own about seven pairs but could easily survive with three: a light, a dark and a black.\nGiven Friday is , it is timely to share the stories of two people in the fashion industry who are slowing denim consumption by producing one-of-a-kind pieces using very different techniques.\nSydney native Kai Brown got the idea for  after his grandmother, a "master seamstress", made him a jacket with a Native American Indian blanket he found while on tour (he was a guitarist and surfer before he started the brand).\n\nSubtle statement ... Bella Hadid wearing an embroidered denim jacket on the streets of New York. Photo: Josiah Kamau\n\n"I kept getting stopped all the time [and asked about the jacket]. It\'s still in the office, hanging on the wall. People who know me ... see that jacket and say, \'you\'ve come so far\'," Brown says.\nAll My Relations takes vintage denim pieces and, using decades-old chain-stitch embroidery techniques, creates one-off pieces.\nBrown aims to create clothes that inspire an "emotional reaction", as a counterpoint to the homogenous nature of fast fashion.\n"People will bring me a [new] jacket but I will educate them ... if you\'re going to get some work done it\'s worth getting a quality vintage piece," he says.\n\nThe best denim is vintage denim, especially when you wear it like Gigi Hadid. Photo: Christian Vierig\n\nBoth Brown and Sarah Darby, of , agree choosing a design for a custom-made jacket is a little like getting a tattoo, albeit one you can take off.\nIn fact, it was Darby\'s desire for ink but her inability to commit that led the fashion illustrator to create her brand, which produces painted designs on vintage denim and leather.\nHer celebrity clients include model Stephanie Claire Smith and The Bachelorette\'s Georgia Love.\nDarby recalls one client, who had struggled with body image her whole life, having "sparkling as I am" embroidered on the cuffs of her jacket.\n"I get to know someone so that when I hand [the jacket] over, it\'s with love," she says.\nDarby uses about 90 per cent salvaged denim for her designs, including Levi\'s jackets that need soaking for two days to rid them of 30 years\' worth of grime.\nClare Press, , author and host of the Wardrobe Crisis podcast, says jeans have become "our unofficial global uniform" and we need to be more mindful of the impact they have on the planet and the people who make them.\nShe says more than 260 million pairs of jeans are made for export in Xintang, aka China\'s "Jeans Town", where the toxic run-off from production turns the waterways blue and affects the health of the workers.\n"According to Greenpeace, high levels of lead and copper pollute the riverbed. The dust in the streets is blue. When it rains, the puddles are blue too. The air stinks," she says.\nShe  encourages consumers  to avoid paying top dollar for artificially aged and distressed denim and instead embrace the natural ageing process.\n"The whole idea behind that sort of look as a badge of honour was that your favourite pair of jeans had earned those makers of age. That they had a story to tell. Today, that story is less than authentic."\nGenes for Jeans Day is on Friday, August 4. Find out more at jeansforgenes.org.au.\nGet the look\n\nAlexander McQueen at Stylebop.com, $2322 (approx).\n\nMCQ Alexander McQueen at Stylebop.com, $264 (approx).\n\nAll My Relations, $2295.\n\nKowtow, $229.\n\nASOS, $70.\n\nJeanswest, $119.\n\nNeed more inspiration? Shop our editor\'s picks\n\n',
             'sindices': [{'name': 'MCQ Alexander McQueen', 'count': 1.0, 'score': 0.0},
                          {'name': 'Sarah Darby', 'count': 1.0, 'score': 2.0},
                          {'name': 'Christian Vierig', 'count': 1.0, 'score': 0.0},
                          {'name': 'Getty Images', 'count': 1.0, 'score': 0.0},
                          {'name': 'Native American Indian', 'count': 1.0, 'score': 0.0},
                          {'name': 'Levi', 'count': 1.0, 'score': 4.0},
                          {'name': "Bachelorette's Georgia Love", 'count': 1.0, 'score': 0.0},
                          {'name': 'Relations, $2295', 'count': 1.0, 'score': 0.0},
                          {'name': 'Photo', 'count': 3.0, 'score': 0.0},
                          {'name': 'Greenpeace', 'count': 1.0, 'score': 3.0},
                          {'name': 'Darby', 'count': 3.0, 'score': 1.0}, {'name': 'China', 'count': 1.0, 'score': -2.0},
                          {'name': 'Clare Press', 'count': 1.0, 'score': 0.0},
                          {'name': 'Stylebop', 'count': 2.0, 'score': 0.0},
                          {'name': 'Wardrobe Crisis', 'count': 1.0, 'score': 0.0},
                          {'name': 'Bella Hadid', 'count': 1.0, 'score': -1.0},
                          {'name': 'Portobello Road Market', 'count': 1.0, 'score': 0.0},
                          {'name': 'New York', 'count': 1.0, 'score': 0.0},
                          {'name': 'Jeans Town', 'count': 1.0, 'score': -2.0},
                          {'name': 'Friday', 'count': 2.0, 'score': 1.0},
                          {'name': 'Jeans Day', 'count': 1.0, 'score': 0.0},
                          {'name': 'Gigi Hadid', 'count': 1.0, 'score': 0.0},
                          {'name': 'Stephanie Claire Smith', 'count': 1.0, 'score': 2.0},
                          {'name': 'August 4', 'count': 1.0, 'score': 0.0},
                          {'name': 'Kesha', 'count': 1.0, 'score': 1.0},
                          {'name': 'ASOS, $70', 'count': 1.0, 'score': 0.0},
                          {'name': 'Alexander McQueen', 'count': 1.0, 'score': 0.0},
                          {'name': 'Josiah Kamau', 'count': 1.0, 'score': 0.0},
                          {'name': 'Jeanswest, $119', 'count': 1.0, 'score': 0.0},
                          {'name': 'Brown', 'count': 3.0, 'score': 3.0},
                          {'name': 'Xintang', 'count': 1.0, 'score': 0.0},
                          {'name': 'Kai Brown', 'count': 1.0, 'score': 0.0},
                          {'name': 'Sydney', 'count': 1.0, 'score': 0.0}],
             'datetime': datetime.datetime(2017, 7, 30, 21, 11)}]

        client.add_articles(data)
